package com.wigo.android.core.server.dto;

public enum StatusCategory {
    DINING_EVENT, IT, FESTIVAL_EVENT, COMEDY_EVENT, FITNESS, SHOPPING, RELIGIOUS_EVENT,
    FOOD_TASTING, VOLUNTEERING, BOOK_EVENT, MOVIE_EVENT, DANCE_EVENT, NIGHTLIFE, ART_EVENT, SPORTS_EVENT, THEATER_EVENT, CONFERENCE_EVENT, FAMILY_EVENT, MEETUP, LECTURE,
    MUSIC_EVENT, WORKSHOP, CHAT, CELEBRATION, ACTIVITY, OTHER
}
